# Generated by Django 5.1.3 on 2024-11-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
