# Generated by Django 5.1.3 on 2024-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_alter_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='userid',
            field=models.CharField(max_length=200),
        ),
    ]
