# Generated by Django 5.1.3 on 2024-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_alter_register_password_alter_register_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(max_length=8),
        ),
    ]
